apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilgang
  namespace: aap
  labels:
    team: aap
    sub: tilgang
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  ingresses:
    - https://aap-tilgang.intern.dev.nav.no
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          {{#each roles}}
          - id: "{{this.group}}"
          {{/each}}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  redis:
    - instance: tilgang
      access: readwrite
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  secureLogs:
    enabled: true
  env:
  {{#each roles as |role|}}
    - name: "{{role.name}}"
      value: "{{role.group}}"
  {{/each}}
    - name: PDL_BASE_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_AUDIENCE
      value: dev-fss:pdl:pdl-api
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: MS_GRAPH_BASE_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: BEHANDLINGSFLYT_BASE_URL
      value: http://behandlingsflyt
    - name: BEHANDLINGSFLYT_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: SKJERMING_BASE_URL
      value: http://skjermede-personer-pip.nom
    - name: SKJERMING_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: NOM_BASE_URL
      value: http://nom-api.nom/graphql
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
    outbound:
      rules:
        - application: behandlingsflyt
        - application: nom-api
          namespace: nom
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: pdl-api.dev-fss-pub.nais.io
