isdev: true
ingress: https://aap-tilgang.intern.dev.nav.no
roles:
  - name: AAP_BESLUTTER
    ad: 0000-GA-AAP_BESLUTTER
    group: f0f6cad5-e3c0-4308-99a2-3630ac60174a

    #NKS og andre nysgjerrige
  - name: AAP_LES
    ad: 0000-GA-AAP_LES
    group: 96e18023-db50-45f7-b023-3251279df28d

  - name: AAP_SAKSBEHANDLER_OPPFOLGING
    ad: 0000-GA-AAP_SAKSBEHANDLER_OPPFOLGING
    group: 33e00155-169b-41e5-8a3f-5582ed975a15

  - name: AAP_KVALITETSSIKRER
    ad: 0000-GA-AAP_KVALITETSSIKRER
    group: c3e18aef-a7ac-49df-806e-4fe58b81460d

  - name: AAP_SAKSBEHANDLER_NASJONAL
    ad: 0000-GA-AAP_SAKSBEHANDLER_NASJONAL
    group: 3377dc51-ca61-4e36-b812-21b5fc34474f

  - name: AAP_DRIFT
    ad: 0000-GA-AAP_DRIFT
    group: bc89623f-4624-4978-ac54-acd048c0f2a5

  - name: AAP_PRODUKSJONSSTYRING
    ad: 0000-GA-AAP_PRODUKSJONSSTYRING
    group: c75883f9-4cb2-42c7-b75c-3f0f29ee3ead
env:
  - name: PDL_BASE_URL
    value: https://pdl-api.dev-fss-pub.nais.io/graphql
  - name: PDL_AUDIENCE
    value: dev-fss:pdl:pdl-api
  - name: PDL_SCOPE
    value: api://dev-fss.pdl.pdl-api/.default
  - name: SAF_BASE_URL
    value: https://saf-q2.dev-fss-pub.nais.io/graphql
  - name: SAF_SCOPE
    value: api://dev-fss.teamdokumenthandtering.saf/.default
  - name: MS_GRAPH_BASE_URL
    value: https://graph.microsoft.com/v1.0/
  - name: MS_GRAPH_SCOPE
    value: https://graph.microsoft.com/.default
  - name: BEHANDLINGSFLYT_BASE_URL
    value: http://behandlingsflyt
  - name: BEHANDLINGSFLYT_SCOPE
    value: api://dev-gcp.aap.behandlingsflyt/.default
  - name: SKJERMING_BASE_URL
    value: http://skjermede-personer-pip.nom
  - name: SKJERMING_SCOPE
    value: api://dev-gcp.nom.skjermede-personer-pip/.default
  - name: NOM_BASE_URL
    value: http://nom-api.nom/graphql
  - name: NOM_SCOPE
    value: api://dev-gcp.nom.nom-api/.default
  - name: FORTROLIG_ADRESSE_AD
    value: ea930b6b-9397-44d9-b9e6-f4cf527a632a # 0000-GA-Fortrolig_Adresse
  - name: STRENGT_FORTROLIG_ADRESSE_AD
    value: 5ef775f2-61f8-4283-bf3d-8d03f428aa14 #0000-GA-Strengt_Fortrolig_Adresse
  - name: SKJERMEDE_PERSONER_AD
    value: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d # 0000-GA-Egne_ansatte TODO: Oppdater disse
external-outbound-hosts:
  - value: saf.dev-fss-pub.nais.io
  - value: pdl-api.dev-fss-pub.nais.io