roles:
  #NAY
  - name: AAP_SAKSBEHANDLER
    ad: 0000-GA-AAP_SAKSBEHANDLER
    group: 8bb0ee13-49cd-4e75-8c3d-a13420c8b376
  
  - name: AAP_BESLUTTER
    ad: 0000-GA-AAP_BESLUTTER
    group: f0f6cad5-e3c0-4308-99a2-3630ac60174a

    #Lokalkontor
  - name: AAP_VEILEDER
    ad: 0000-GA-AAP_VEILEDER
    group: 12353679-aa80-4e59-bb47-95e727bfe85c
  
    #TODO: Trenger vi denne?
  - name: AAP_FATTER
    ad: 0000-GA-AAP_FATTER
    group: b60d74dd-fcf7-4c53-a50b-7b20f51804a1

    #NKS og andre nysgjerrige
  - name: AAP_LES
    ad: 0000-GA-AAP_LES
    group: 96e18023-db50-45f7-b023-3251279df28d
    
  # TODO: Utvikler, avdelingsleder