roles:
  #NAY
  - name: AAP_SAKSBEHANDLER
    ad: 0000-GA-AAP_SAKSBEHANDLER
    group: 8bb0ee13-49cd-4e75-8c3d-a13420c8b376
  
  - name: AAP_BESLUTTER
    ad: 0000-GA-AAP_BESLUTTER
    group: f0f6cad5-e3c0-4308-99a2-3630ac60174a

    #Lokalkontor
  - name: AAP_VEILEDER
    ad: 0000-GA-AAP_VEILEDER
    group: 12353679-aa80-4e59-bb47-95e727bfe85c

    #NKS og andre nysgjerrige
  - name: AAP_LES
    ad: 0000-GA-AAP_LES
    group: 96e18023-db50-45f7-b023-3251279df28d

  - name: AAP_SAKSBEHANDLER_OPPFOLGING
    ad: 0000-GA-AAP_SAKSBEHANDLER_OPPFOLGING
    group: 33e00155-169b-41e5-8a3f-5582ed975a15

  - name: AAP_KVALITETSSIKRER
    ad: 0000-GA-AAP_KVALITETSSIKRER
    group: c3e18aef-a7ac-49df-806e-4fe58b81460d

  - name: AAP_SAKSBEHANDLER_NASJONAL
    ad: 0000-GA-AAP_SAKSBEHANDLER_NASJONAL
    group: 3377dc51-ca61-4e36-b812-21b5fc34474f

  - name: AAP_DRIFT
    ad: 0000-GA-AAP_DRIFT
    group: bc89623f-4624-4978-ac54-acd048c0f2a5

  - name: AAP_PRODUKSJONSSTYRING
    ad: 0000-GA-AAP_PRODUKSJONSSTYRING
    group: c75883f9-4cb2-42c7-b75c-3f0f29ee3ead