apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilgang
  namespace: aap
  labels:
    team: aap
    sub: tilgang
spec:
  image: {{image}}
  {{#if isdev}}
  ingresses:
    - {{ingress}}
  {{/if}}
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          {{#each roles}}
          - id: "{{this.group}}"
          {{/each}}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  valkey:
    - instance: tilgang
      access: readwrite
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  env:
  {{#each roles as |role|}}
    - name: "{{role.name}}"
      value: "{{role.group}}"
  {{/each}}
  {{#each env as |e|}}
    - name: "{{e.name}}"
      value: "{{e.value}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
        - application: postmottak-backend
        - application: oppgave
        - application: saksbehandling
        - application: dokumentinnhenting
        - application: api-intern
        {{#if isdev}}
        - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod.yaml
        - application: azure-token-generator
          namespace: nais
        {{/if}}
    outbound:
      rules:
        - application: behandlingsflyt
        - application: nom-api
          namespace: nom
        - application: skjermede-personer-pip
          namespace: nom
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
      external:
      {{#each external-outbound-hosts as |host|}}
        - host: "{{host.value}}"
      {{/each}}
