apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilgang
  namespace: aap
  labels:
    team: aap
    sub: tilgang
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 80
    max: 2
    min: 1
  ingresses:
    - {{ingress}}
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          {{#each roles}}
          - id: "{{this.group}}"
          {{/each}}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  valkey:
    - instance: tilgang
      access: readwrite
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  env:
  {{#each roles as |role|}}
    - name: "{{role.name}}"
      value: "{{role.group}}"
  {{/each}}
  {{#each env as |e|}}
    - name: "{{e.name}}"
      value: "{{e.value}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
        - application: postmottak-backend
        - application: oppgave
        - application: saksbehandling
    outbound:
      rules:
        - application: behandlingsflyt
        - application: nom-api
          namespace: nom
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
