isdev: 0
ingress: https://aap-tilgang.intern.nav.no
roles:
  - name: AAP_BESLUTTER
    ad: 0000-GA-AAP_BESLUTTER
    group: 5763b52f-f16a-483d-8f40-25be9de95c0a

    #NKS og andre nysgjerrige
  - name: AAP_LES
    ad: 0000-GA-AAP_LES
    group: 963df3e5-04f7-415e-8d13-1de981603940

  - name: AAP_SAKSBEHANDLER_OPPFOLGING
    ad: 0000-GA-AAP_SAKSBEHANDLER_OPPFOLGING
    group: dc8b0182-1449-445a-833c-1a4620b7c2be

  - name: AAP_KVALITETSSIKRER
    ad: 0000-GA-AAP_KVALITETSSIKRER
    group: a6bf143f-fee9-41ab-a487-f54503a28de6

  - name: AAP_SAKSBEHANDLER_NASJONAL
    ad: 0000-GA-AAP_SAKSBEHANDLER_NASJONAL
    group: 3a65f41a-b3f3-4b1c-830a-df20ff020980

  - name: AAP_DRIFT
    ad: 0000-GA-AAP_DRIFT
    group: ff9a228b-4aab-47bd-8aee-598d80f0fb4b

  - name: AAP_PRODUKSJONSSTYRING
    ad: 0000-GA-AAP_PRODUKSJONSSTYRING
    group: 1d61ecf2-fcca-4dbb-ba49-82ab01aef96e
env:
  - name: PDL_BASE_URL
    value: https://pdl-api.prod-fss-pub.nais.io/graphql
  - name: PDL_AUDIENCE
    value: dev-fss:pdl:pdl-api
  - name: PDL_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default
  - name: SAF_BASE_URL
    value: https://safselvbetjening.prod-fss-pub.nais.io
  - name: SAF_SCOPE
    value: prod-fss:teamdokumenthandtering:safselvbetjening
  - name: MS_GRAPH_BASE_URL
    value: https://graph.microsoft.com/v1.0/
  - name: MS_GRAPH_SCOPE
    value: https://graph.microsoft.com/.default
  - name: BEHANDLINGSFLYT_BASE_URL
    value: http://behandlingsflyt
  - name: BEHANDLINGSFLYT_SCOPE
    value: api://prod-gcp.aap.behandlingsflyt/.default
  - name: SKJERMING_BASE_URL
    value: http://skjermede-personer-pip.nom
  - name: SKJERMING_SCOPE
    value: api://prod-gcp.nom.skjermede-personer-pip/.default
  - name: NOM_BASE_URL
    value: http://nom-api.nom/graphql
  - name: NOM_SCOPE
    value: api://prod-gcp.nom.nom-api/.default
  - name: FORTROLIG_ADRESSE_AD
    value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b # 0000-GA-Fortrolig_Adresse
  - name: STRENGT_FORTROLIG_ADRESSE_AD
    value: ad7b87a6-9180-467c-affc-20a566b0fec0 # 0000-GA-Strengt_Fortrolig_Adresse
  - name: SKJERMEDE_PERSONER_AD
    value: e750ceb5-b70b-4d94-b4fa-9d22467b786b # 0000-GA-Egne_ansatte
external-outbound-hosts:
  - value: saf.prod-fss-pub.nais.io
  - value: pdl-api.prod-fss-pub.nais.io
