[versions]
komponenter = "2.0.163"

[libraries]
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }

behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version = "0.0.663" }
postmottakKontrakt = { module = "no.nav.aap.postmottak:kontrakt", version = "6.0.10" }

ktorOpenApiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }

lettuce = { module = "io.lettuce:lettuce-core", version = "7.7.0.RELEASE" }
coroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version = "1.11.0" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.11.0" }
testcontainersRedis = { module = "com.redis:testcontainers-redis", version = "2.2.4" }