/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun appHasAGreeting() {
        assertTrue(true)
    }
}
